Repository the-mentors/the-mentors-backend, pull requests merged in 2023-03, with the labels that each got.

#6 feat: 카테고리 전체 조회 기능
  mentors-domain/build.gradle
  mentors-domain/src/main/java/com/mentors/category/domain/Category.java
  mentors-domain/src/main/java/com/mentors/category/domain/CategoryCode.java
  mentors-domain/src/main/java/com/mentors/category/mapper/CategoryDomainMapper.java
  mentors-domain/src/main/java/com/mentors/category/service/CategoryReadService.java
  mentors-domain/src/main/java/com/mentors/category/service/CategoryReadServiceImpl.java
  mentors-domain/src/main/resources/application.properties
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/category/CategoryEntity.java
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/category/CategoryRepository.java
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/global/common/BaseEntity.java
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/global/config/JpaConfiguration.java
  mentors-infrastruct/persistence-database/src/main/resources/application-persistence-database.yml
  mentors-infrastruct/persistence-database/src/main/resources/db/migration/V001__Create_Categories.sql
  mentors-infrastruct/persistence-database/src/main/resources/db/seed/R__001_Seed_Categories.sql
  mentors-interface/http/category.http
  mentors-interface/src/main/java/com/mentors/api/category/controller/CategoryApiController.java
  mentors-interface/src/main/java/com/mentors/api/category/dto/CategoryRequest.java
  mentors-interface/src/main/java/com/mentors/api/category/mapper/CategoryApiMapper.java
  mentors-interface/src/main/java/com/mentors/api/category/usecase/GetAllCategoryUsecase.java
  mentors-interface/src/test/java/com/mentors/document/Documentation.java
Labels: ⚡기능, 💻백엔드

#10 feat: 카테고리 전체 조회 테스트 코드 작성
  .gitignore
  mentors-domain/build.gradle
  mentors-domain/src/main/java/com/mentors/category/mapper/CategoryDomainMapper.java
  mentors-domain/src/main/java/com/mentors/category/service/CategoryReadServiceImpl.java
  mentors-domain/src/test/java/com/mentors/TestSpringbootContainer.java
  mentors-domain/src/test/java/com/mentors/category/mapper/CategoryDomainMapperTest.java
  mentors-domain/src/test/java/com/mentors/category/service/CategoryReadServiceTest.java
  mentors-domain/src/test/java/com/mentors/support/BasicClassTest.java
  mentors-domain/src/test/java/com/mentors/support/DatabaseCleaner.java
  mentors-domain/src/test/java/com/mentors/support/ServiceTest.java
  mentors-domain/src/test/resources/application.yml
  mentors-domain/src/testFixtures/java/com/mentors/CategoryFixture.java
  mentors-infrastruct/persistence-database/src/main/resources/application-persistence-database-test.yml
  mentors-infrastruct/persistence-database/src/test/java/com/mentors/persistencedatabase/PersistenceDatabaseApplicationTests.java
  mentors-interface/build.gradle
  mentors-interface/src/docs/asciidoc/category.adoc
  mentors-interface/src/docs/asciidoc/index.adoc
  mentors-interface/src/main/resources/static/docs/category.html
  mentors-interface/src/main/resources/static/docs/index.html
  mentors-interface/src/test/java/com/mentors/MentorsInterfaceApplicationTests.java
  mentors-interface/src/test/java/com/mentors/api/category/controller/CategoryApiControllerTest.java
  mentors-interface/src/test/java/com/mentors/api/category/mapper/CategoryApiMapperTest.java
  mentors-interface/src/test/java/com/mentors/api/category/usecase/GetAllCategoryUsecaseTest.java
  mentors-interface/src/test/java/com/mentors/document/CategoryDocumentation.java
  mentors-interface/src/test/java/com/mentors/document/Documentation.java
  mentors-interface/src/test/java/com/mentors/document/DocumentationFixture.java
  mentors-interface/src/test/java/com/mentors/support/BasicClassTest.java
  mentors-interface/src/test/java/com/mentors/support/RestApiTest.java
  mentors-interface/src/test/java/com/mentors/support/UsecaseTest.java
  mentors-interface/src/test/resources/application.yml
Labels: 📃문서화, ⚡기능, 💻백엔드

#12 merge: 카테고리 전체조회, 유저 회원가입 기능
  .gitignore
  mentors-domain/build.gradle
  mentors-domain/src/main/java/com/mentors/category/domain/Category.java
  mentors-domain/src/main/java/com/mentors/category/domain/CategoryCode.java
  mentors-domain/src/main/java/com/mentors/category/mapper/CategoryDomainMapper.java
  mentors-domain/src/main/java/com/mentors/category/service/CategoryReadService.java
  mentors-domain/src/main/java/com/mentors/category/service/CategoryReadServiceImpl.java
  mentors-domain/src/main/java/com/mentors/user/domain/Role.java
  mentors-domain/src/main/java/com/mentors/user/domain/User.java
  mentors-domain/src/main/java/com/mentors/user/mapper/UserDomainMapper.java
  mentors-domain/src/main/java/com/mentors/user/service/UserWriteService.java
  mentors-domain/src/main/java/com/mentors/user/service/UserWriteServiceImpl.java
  mentors-domain/src/main/resources/application.properties
  mentors-domain/src/test/java/com/mentors/TestSpringbootContainer.java
  mentors-domain/src/test/java/com/mentors/category/mapper/CategoryDomainMapperTest.java
  mentors-domain/src/test/java/com/mentors/category/service/CategoryReadServiceTest.java
  mentors-domain/src/test/java/com/mentors/support/BasicClassTest.java
  mentors-domain/src/test/java/com/mentors/support/DatabaseCleaner.java
  mentors-domain/src/test/java/com/mentors/support/ServiceTest.java
  mentors-domain/src/test/resources/application.yml
  mentors-domain/src/testFixtures/java/com/mentors/CategoryFixture.java
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/category/CategoryEntity.java
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/category/CategoryRepository.java
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/global/common/BaseEntity.java
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/global/config/JpaConfiguration.java
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/user/UserEntity.java
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/user/UserRepository.java
  mentors-infrastruct/persistence-database/src/main/resources/application-persistence-database-test.yml
  mentors-infrastruct/persistence-database/src/main/resources/application-persistence-database.yml
  mentors-infrastruct/persistence-database/src/main/resources/db/migration/V001__Create_Categories.sql
  mentors-infrastruct/persistence-database/src/main/resources/db/seed/R__001_Seed_Categories.sql
  mentors-infrastruct/persistence-database/src/test/java/com/mentors/persistencedatabase/PersistenceDatabaseApplicationTests.java
  mentors-interface/build.gradle
  mentors-interface/http/category.http
  mentors-interface/src/docs/asciidoc/category.adoc
  mentors-interface/src/docs/asciidoc/index.adoc
  mentors-interface/src/main/java/com/mentors/api/category/controller/CategoryApiController.java
  mentors-interface/src/main/java/com/mentors/api/category/dto/CategoryRequest.java
  mentors-interface/src/main/java/com/mentors/api/category/mapper/CategoryApiMapper.java
  mentors-interface/src/main/java/com/mentors/api/category/usecase/GetAllCategoryUsecase.java
  mentors-interface/src/main/java/com/mentors/api/user/controller/UserApiController.java
  mentors-interface/src/main/java/com/mentors/api/user/dto/UserSignUpRequest.java
  mentors-interface/src/main/java/com/mentors/api/user/mapper/UserApiMapper.java
  mentors-interface/src/main/java/com/mentors/api/user/usecase/SignUpUserUsecase.java
  mentors-interface/src/main/java/com/mentors/global/config/SecurityConfig.java
  mentors-interface/src/main/resources/static/docs/category.html
  mentors-interface/src/main/resources/static/docs/index.html
  mentors-interface/src/test/java/com/mentors/MentorsInterfaceApplicationTests.java
  mentors-interface/src/test/java/com/mentors/api/category/controller/CategoryApiControllerTest.java
  mentors-interface/src/test/java/com/mentors/api/category/mapper/CategoryApiMapperTest.java
  mentors-interface/src/test/java/com/mentors/api/category/usecase/GetAllCategoryUsecaseTest.java
  mentors-interface/src/test/java/com/mentors/document/CategoryDocumentation.java
  mentors-interface/src/test/java/com/mentors/document/Documentation.java
  mentors-interface/src/test/java/com/mentors/document/DocumentationFixture.java
  mentors-interface/src/test/java/com/mentors/support/BasicClassTest.java
  mentors-interface/src/test/java/com/mentors/support/RestApiTest.java
  mentors-interface/src/test/java/com/mentors/support/UsecaseTest.java
  mentors-interface/src/test/resources/application.yml
Labels: 👌머지, 💻백엔드

#16 docs: 깃허브 리포지토리 대표언어 설정
  .gitattributes
Labels: 📃문서화, 💻백엔드

#19 feat: 유저 정보 수정 기능 및 테스트
  mentors-domain/build.gradle
  mentors-domain/src/main/java/com/mentors/user/service/UserWriteService.java
  mentors-domain/src/main/java/com/mentors/user/service/UserWriteServiceImpl.java
  mentors-domain/src/test/java/com/mentors/support/DatabaseCleaner.java
  mentors-domain/src/test/java/com/mentors/user/service/UserWriteServiceTest.java
  mentors-domain/src/testFixtures/java/com/mentors/UserFixture.java
  mentors-infrastruct/persistence-database/build.gradle
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/user/UserEntity.java
  mentors-infrastruct/persistence-database/src/test/java/com/mentors/user/UserEntityTest.java
  mentors-infrastruct/persistence-database/src/testFixtures/java/com/mentors/CategoryEntityFixture.java
  mentors-infrastruct/persistence-database/src/testFixtures/java/com/mentors/UserEntityFixture.java
  mentors-interface/src/docs/asciidoc/category.adoc
  mentors-interface/src/docs/asciidoc/index.adoc
  mentors-interface/src/docs/asciidoc/user.adoc
  mentors-interface/src/main/java/com/mentors/api/user/controller/UserApiController.java
  mentors-interface/src/main/java/com/mentors/api/user/dto/UserEditRequest.java
  mentors-interface/src/main/java/com/mentors/api/user/mapper/UserApiMapper.java
  mentors-interface/src/main/java/com/mentors/api/user/usecase/EditUserUsecase.java
  mentors-interface/src/test/java/com/mentors/api/user/controller/UserApiControllerTest.java
  mentors-interface/src/test/java/com/mentors/api/user/mapper/UserApiMapperTest.java
  mentors-interface/src/test/java/com/mentors/api/user/usecase/EditUserUsecaseTest.java
  mentors-interface/src/test/java/com/mentors/document/Documentation.java
  mentors-interface/src/test/java/com/mentors/document/UserDocumentation.java
  mentors-interface/src/test/java/com/mentors/support/fixture/UserFixture.java
Labels: 📃문서화, ⚡기능, 💻백엔드

#24 feat: 유저 정보수정 기능, 유저 회원가입 및 정보 수정 테스트, 유저 로그인 기능
  mentors-domain/build.gradle
  mentors-domain/src/main/java/com/mentors/authToken/domain/AuthToken.java
  mentors-domain/src/main/java/com/mentors/authToken/mapper/AuthTokenDomainMapper.java
  mentors-domain/src/main/java/com/mentors/authToken/service/AuthTokenReadService.java
  mentors-domain/src/main/java/com/mentors/authToken/service/AuthTokenReadServiceImpl.java
  mentors-domain/src/main/java/com/mentors/authToken/service/AuthTokenWriteService.java
  mentors-domain/src/main/java/com/mentors/authToken/service/AuthTokenWriteServiceImpl.java
  mentors-domain/src/main/java/com/mentors/user/domain/User.java
  mentors-domain/src/main/java/com/mentors/user/mapper/UserDomainMapper.java
  mentors-domain/src/main/java/com/mentors/user/service/UserReadService.java
  mentors-domain/src/main/java/com/mentors/user/service/UserReadServiceImpl.java
  mentors-domain/src/main/java/com/mentors/user/service/UserWriteService.java
  mentors-domain/src/main/java/com/mentors/user/service/UserWriteServiceImpl.java
  mentors-domain/src/test/java/com/mentors/support/DatabaseCleaner.java
  mentors-domain/src/test/java/com/mentors/user/mapper/UserDomainMapperTest.java
  mentors-domain/src/test/java/com/mentors/user/service/UserWriteServiceTest.java
  mentors-domain/src/testFixtures/java/com/mentors/UserFixture.java
  mentors-infrastruct/persistence-database/build.gradle
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/authToken/AuthTokenEntity.java
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/authToken/AuthTokenRepository.java
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/user/UserEntity.java
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/user/UserRepository.java
  mentors-infrastruct/persistence-database/src/test/java/com/mentors/user/UserEntityTest.java
  mentors-infrastruct/persistence-database/src/testFixtures/java/com/mentors/CategoryEntityFixture.java
  mentors-infrastruct/persistence-database/src/testFixtures/java/com/mentors/UserEntityFixture.java
  mentors-interface/build.gradle
  mentors-interface/src/docs/asciidoc/category.adoc
  mentors-interface/src/docs/asciidoc/index.adoc
  mentors-interface/src/docs/asciidoc/user.adoc
  mentors-interface/src/main/java/com/mentors/api/user/controller/UserApiController.java
  mentors-interface/src/main/java/com/mentors/api/user/dto/UserEditRequest.java
  mentors-interface/src/main/java/com/mentors/api/user/dto/UserSignInRequest.java
  mentors-interface/src/main/java/com/mentors/api/user/dto/UserSignUpRequest.java
  mentors-interface/src/main/java/com/mentors/api/user/mapper/UserApiMapper.java
  mentors-interface/src/main/java/com/mentors/api/user/usecase/EditUserUsecase.java
  mentors-interface/src/main/java/com/mentors/api/user/usecase/SignInUserUsecase.java
  mentors-interface/src/main/java/com/mentors/global/config/SecurityConfig.java
  mentors-interface/src/main/java/com/mentors/global/jwt/AuthTokenCreator.java
  mentors-interface/src/main/java/com/mentors/global/jwt/JwtTokenProvider.java
  mentors-interface/src/main/java/com/mentors/global/jwt/TokenCreator.java
  mentors-interface/src/main/java/com/mentors/global/jwt/TokenProvider.java
  mentors-interface/src/main/java/com/mentors/global/jwt/dto/AuthTokenInterface.java
  mentors-interface/src/main/java/com/mentors/global/jwt/mapper/AuthInterfaceMapper.java
  mentors-interface/src/main/resources/application-jwt.yml
  mentors-interface/src/main/resources/application.yml
  mentors-interface/src/test/java/com/mentors/api/user/controller/UserApiControllerTest.java
  mentors-interface/src/test/java/com/mentors/api/user/mapper/UserApiMapperTest.java
  mentors-interface/src/test/java/com/mentors/api/user/usecase/EditUserUsecaseTest.java
  mentors-interface/src/test/java/com/mentors/api/user/usecase/SignUpUserUsecaseTest.java
  mentors-interface/src/test/java/com/mentors/document/Documentation.java
  mentors-interface/src/test/java/com/mentors/document/UserDocumentation.java
  mentors-interface/src/test/java/com/mentors/support/RestApiTest.java
  mentors-interface/src/test/java/com/mentors/support/fixture/UserFixture.java
Labels: 🕷버그, 📃문서화, ⚡기능, 💻백엔드

#28 feat: 예외처리를 위한 ControllerAdvice 추가
  mentors-interface/src/main/java/com/mentors/global/error/ApiControllerAdvice.java
  mentors-interface/src/main/java/com/mentors/global/error/ErrorResponse.java
Labels: ⚡기능, 💻백엔드

#33 feat & fix : 멘토링 엔티티 설계 및 모듈간 참조 버그 수정
  build.gradle
  mentors-commons/common-domain/src/main/java/com/mentors/mentoring/LinkType.java
  mentors-domain/build.gradle
  mentors-infrastruct/persistence-database/build.gradle
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/mentoring/category/MentoringCategoryEntity.java
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/mentoring/category/MentoringCategoryRepository.java
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/mentoring/hashtag/HashTagEntity.java
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/mentoring/hashtag/HashTagRepository.java
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/mentoring/hashtag/MentoringHashTagEntity.java
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/mentoring/hashtag/MentoringHashTagRepository.java
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/mentoring/mentoring/MentoringEntity.java
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/mentoring/mentoring/MentoringLinkEntity.java
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/mentoring/mentoring/MentoringLinkRepository.java
  mentors-infrastruct/persistence-database/src/main/java/com/mentors/mentoring/mentoring/MentoringRepository.java
  mentors-infrastruct/persistence-database/src/main/resources/db/migration/V001__Create_Categories.sql
  mentors-infrastruct/persistence-database/src/main/resources/db/migration/V002__Create_Users.sql
  mentors-infrastruct/persistence-database/src/main/resources/db/migration/V003__Create_Mentoring.sql
  mentors-infrastruct/persistence-database/src/main/resources/db/migration/V004__Create_HashTags.sql
  mentors-infrastruct/persistence-database/src/main/resources/db/migration/V005__Create_MentoringHashTags.sql
  mentors-infrastruct/persistence-database/src/main/resources/db/migration/V006__Create_MentoringCategories.sql
  mentors-infrastruct/persistence-database/src/main/resources/db/migration/V007__Create_MentoringLinks.sql
  mentors-interface/build.gradle
Labels: ⚡기능, 💻백엔드, 🛠리팩토링
